app = "backend"  # Replace with your app's name on Fly.io

[build]
  image = "php:8.1-fpm"  # You can use an image suitable for PHP (like the one from the Dockerfile)

  # Optional: Build Dockerfile if you have one
  dockerfile = "./Dockerfile"

[env]
  # Set necessary environment variables here, like your database credentials, app key, etc.
  APP_ENV = "production"
  APP_KEY = "base64:QZh7vIBm4Q5WuT1qnItA0n0o7FtA0K5Z7A7kXCxzGss"
  DB_CONNECTION = "mysql"
  DB_HOST = "gateway01.us-west-2.prod.aws.tidbcloud.com"
  DB_PORT = "4000"
  DB_DATABASE = "enrollment"
  DB_USERNAME = "RjMQMLXQ7RFbknU.root"
  DB_PASSWORD = "zaeyrF32jZL5RSYR"

[[services]]
  internal_port = 80  # The port your app listens to internally (if using Nginx or Apache, set this to 80)

  # The port Fly.io will expose publicly
  ports = [{ port = 80, handlers = ["http"] }]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  # Optional: Set health check
  health_checks = [
    { path = "/health", interval = "10s", timeout = "2s", threshold = 3, method = "GET" }
  ]

[experimental]
  # Optional: Configure fly.io's experimental features like automatic scaling
  auto_rollback = true
