[phases.setup]
# Install PHP dependencies
commands = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
# Run Laravel optimizations
commands = ["php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[phases.deploy]
# Start the Laravel application
commands = ["php artisan serve --host=0.0.0.0 --port=$PORT"]